import type { ClientRecord } from '../../store/useCabinetStore'
import type { AssetLine, DiscoveryFormState } from './discovery.types'

// Valeur initiale d'une ligne d'actif avec tous les nouveaux champs
export function buildEmptyAssetLine(overrides?: Partial<AssetLine>): AssetLine {
  return {
    id: '',
    label: '',
    category: 'Liquidités',
    envelopeType: 'Compte courant',
    holderPersonId: 'household',
    institution: '',
    amount: 0,
    available: true,
    comment: '',
    // Nouveaux champs
    openingDate: '',
    totalContributions: 0,
    holder: 'Souscripteur principal',
    entryFees: 0,
    managementFees: 0,
    insurerName: '',
    hasEuroFund: true,
    hasUC: false,
    contractQuality: 'Non évalué',
    isEmergencyFund: false,
    ...overrides,
  }
}

export function buildInitialDiscoveryState(client: ClientRecord | null): DiscoveryFormState {
  const parts = client?.fullName.split(' ') ?? []

  return {
    mainPerson: {
      civility: 'Madame',
      firstName: parts[0] === 'Nouveau' ? '' : parts[0] ?? '',
      lastName: parts[0] === 'Nouveau' ? '' : parts.slice(1).join(' ') ?? '',
      birthDate: '',
      email: '',
      phone: '',
      address: '',
      zipCode: '',
      city: '',
      householdStatus: 'Célibataire',
      maritalRegime: 'Non applicable',
      profession: '',
      employmentStatus: 'Salarié',
    },
    linkedPersons: [],
    revenues: [],
    charges: [],
    assets: [],
    liabilities: [],
    tax: {
      taxResidenceCountry: 'France',
      residentInFrance: true,
      commonTaxHousehold: false,
      householdDeclarationType: 'À confirmer',
      numberOfDependentChildrenManual: '',
      useDependentChildrenOverride: false,
      situationFiscaleMode: 'auto',
      taxSituationManual: '',
      partsMode: 'auto',
      partsManual: '',
      taxableIncomeMode: 'auto',
      taxableIncomeManual: '',
      tmiMode: 'auto',
      tmiManual: '',
    },
    investmentProject: {
      investingMode: 'alone',
      fundingMode: 'capacity_only',
      savingsUseMode: 'partial',
      monthlySavingsAmount: 0,
      existingEnvelopesUseMode: 'partial',
      existingEnvelopeUsages: [],
      hasInitialLumpSum: false,
      initialLumpSumAmount: 0,
      hasMonthlyContribution: false,
      monthlyContributionAmount: 0,
    },
    protection: {
      deathCoverage: false,
      disabilityCoverage: false,
      borrowerInsurance: false,
      spouseProtected: false,
      dependantsProtected: false,
      vulnerablePoints: '',
    },
    objectives: {
      mainObjective: 'Diversifier le patrimoine',
      secondaryObjective: '',
      horizonYears: '',
      liquidityNeed: 'Modéré',
      horizonTolerance: 2,
      marketKnowledge: 2,
      investmentExperience: 2,
      drawdownReaction: 2,
      lossCapacity: 2,
      performanceGoal: 2,
      returnVolatilityTradeoff: 2,
      capitalStabilityNeed: 2,
      riskProfileMode: 'auto',
      riskProfileManual: 'Équilibré',
      esgPreference: 'Sans préférence',
      esgImportance: 'Modérée',
      esgThemes: [],
      esgExclusions: [],
      esgComment: '',
    },
    documents: {
      idDocumentReceived: false,
      taxNoticeReceived: false,
      paySlipsReceived: false,
      bankStatementsReceived: false,
      contractsReceived: false,
      missingDocuments: '',
      advisorNotes: '',
    },
    budgetOverrides: {
      householdIncomeMode: 'auto',
      householdIncomeManual: '',
      chargesMode: 'auto',
      chargesManual: '',
      capacityMode: 'auto',
      capacityManual: '',
    },
  }
}
